# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/kasireddymahesh7777@gmail.com/pyspark_dbt_project_dlt")

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from pysparkdbt.bronze.customers

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from pysparkdbt.bronze.drivers

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from pysparkdbt.bronze.locations

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from pysparkdbt.bronze.payments

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from pysparkdbt.bronze.trips

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from pysparkdbt.bronze.vehicles